In [192]:
import pandas as pd
import os

In [193]:
# Daily_shelter = pd.read_csv("C:/Users/karan/Documents/Daily shelter overnight occupancy.csv")
# COVID19_case = pd.read_csv("C:/Users/karan/Documents/COVID19 cases.csv")
# Climate_data = pd.read_csv("C:/Users/karan/Documents/en_climate_daily_ON_6158731_2021_P1D.csv")


# df1 = Daily_shelter.merge(COVID19_case)
# # df1.head()

In [194]:
df = pd.read_csv("C:/Users/karan/Documents/Pandas/Daily shelter overnight occupancy.csv")

files = (file for file in os.listdir('C:/Users/karan/Documents/Pandas'))

df1 = pd.DataFrame()

for file in files:
    df = pd.read_csv("C:/Users/karan/Documents/Pandas/"+file)
    df1 = pd.concat([df1,df])
    
df1.to_csv("df1.csv", index=False)

In [195]:
df1.head()

,Age Group,Assigned_ID,Classification,Client Gender,Currently Hospitalized,Currently Intubated,Currently in ICU,Episode Date,Ever Hospitalized,Ever Intubated,...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,20 to 29 Years,265244.0,PROBABLE,MALE,No,No,No,2022-01-14T00:00:00,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,50 to 59 Years,265245.0,CONFIRMED,MALE,No,No,No,2022-01-13T00:00:00,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,30 to 39 Years,265246.0,CONFIRMED,MALE,No,No,No,2022-01-08T00:00:00,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,40 to 49 Years,265247.0,CONFIRMED,FEMALE,No,No,No,2022-01-13T00:00:00,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,30 to 39 Years,265248.0,PROBABLE,UNKNOWN,No,No,No,2022-01-14T00:00:00,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [196]:
df1.drop(columns=['Ever Hospitalized','Ever Intubated','Ever in ICU','Currently Hospitalized','Currently Intubated','Currently in ICU','Outcome','Neighbourhood Name','Classification'],inplace=True)

df1.tail()

df1.rename(columns={'Reported Date': 'Date'}, inplace=True)
df1.rename(columns={'Ever Hospitalized': 'Hospitalized', 'Ever Intubated': 'Intubated', 'Ever in ICU': 'ICU'}, inplace=True)

In [197]:
df1.tail()

,Age Group,Assigned_ID,Client Gender,Episode Date,FSA,Outbreak Associated,Date,Source of Infection,_id,CAPACITY_ACTUAL_BED,...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.6,NaN,3.6,NaN,4.0,E,9.0,NaN,48.0,NaN
361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.2,NaN,0.2,NaN,2.0,NaN,26.0,NaN,57.0,NaN
362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,T,0.2,NaN,1.0,NaN,NaN,M,NaN,M
363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,M,NaN,M
364,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,0.0,T,NaN,NaN,NaN,M,NaN,M

In [198]:
df1.rename(columns={'LOCATION_POSTAL_CODE': 'POSTAL_CODE', 'Client Gender': 'Gender'}, inplace=True)
df1.head(20)

,Age Group,Assigned_ID,Gender,Episode Date,FSA,Outbreak Associated,Date,Source of Infection,_id,CAPACITY_ACTUAL_BED,...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,20 to 29 Years,265244.0,MALE,2022-01-14T00:00:00,M6H,Sporadic,2022-01-14T00:00:00,No Information,258011.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,50 to 59 Years,265245.0,MALE,2022-01-13T00:00:00,M6K,Sporadic,2022-01-14T00:00:00,No Information,258012.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,30 to 39 Years,265246.0,MALE,2022-01-08T00:00:00,M6G,Sporadic,2022-01-14T00:00:00,No Information,258013.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,40 to 49 Years,265247.0,FEMALE,2022-01-13T00:00:00,M6P,Sporadic,2022-01-14T00:00:00,No Information,258014.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,30 to 39 Years,265248.0,UNKNOWN,2022-01-14T00:00:00,M6K,Outbreak Associated,2022-01-14T00:00:00,"Outbreaks, Congregate Settings",258015.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,20 to 29 Years,265249.0,MALE,2022-01-07T00:00:00,M1R,Sporadic,2022-01-10T00:00:00,No Information,258016.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,70 to 79 Years,265250.0,FEMALE,2022-01-13T00:00:00,M1K,Outbreak Associated,2022-01-14T00:00:00,"Outbreaks, Congregate Settings",258017.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,50 to 59 Years,265251.0,FEMALE,2022-01-14T00:00:00,M4V,Sporadic,2022-01-14T00:00:00,No Information,258018.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,19 and younger,265252.0,UNKNOWN,2022-01-10T00:00:00,M5M,Sporadic,2022-01-14T00:00:00,No Information,258019.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,20 to 29 Years,265253.0,MALE,2021-12-28T00:00:00,M1K,Sporadic,2022-01-12T00:00:00,No Information,258020.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,30 to 39 Years,265254.0,FEMALE,2022-01-14T00:00:00,NaN,Outbreak Associated,2022-01-14T00:00:00,"Outbreaks, Congregate Settings",258021.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,30 to 39 Years,265255.0,MALE,2021-12-31T00:00:00,M1M,Sporadic,2022-01-14T00:00:00,No Information,258022.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,60 to 69 Years,265256.0,FEMALE,2022-01-10T00:00:00,M3L,Outbreak Associated,2022-01-13T00:00:00,Household Contact,258023.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,40 to 49 Years,265257.0,FEMALE,2022-01-07T00:00:00,M4C,Sporadic,2022-01-14T00:00:00,No Information,258024.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,30 to 39 Years,265258.0,MALE,2021-12-29T00:00:00,M4K,Sporadic,2022-01-14T00:00:00,No Information,258025.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,50 to 59 Years,265259.0,MALE,2022-01-07T00:00:00,M9A,Sporadic,2022-01-14T00:00:00,No Information,258026.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,30 to 39 Years,265388.0,MALE,2022-01-12T00:00:00,M1M,Sporadic,2022-01-14T00:00:00,No Information,258155.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,30 to 39 Years,265260.0,FEMALE,2021-12-29T00:00:00,M3C,Sporadic,2022-01-14T00:00:00,No Information,258027.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,60 to 69 Years,265261.0,FEMALE,2021-12-29T00:00:00,M3C,Sporadic,2022-01-14T00:00:00,No Information,258028.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,70 to 79 Years,265262.0,MALE,2021-12-30T00:00:00,M9W,Sporadic,2022-01-14T00:00:00,No Information,258029.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [199]:
print(df1.columns.tolist())

['Age Group', 'Assigned_ID', 'Gender', 'Episode Date', 'FSA', 'Outbreak Associated', 'Date', 'Source of Infection', '_id', 'CAPACITY_ACTUAL_BED', 'CAPACITY_ACTUAL_ROOM', 'CAPACITY_FUNDING_BED', 'CAPACITY_FUNDING_ROOM', 'CAPACITY_TYPE', 'LOCATION_ADDRESS', 'LOCATION_CITY', 'LOCATION_ID', 'LOCATION_NAME', 'POSTAL_CODE', 'LOCATION_PROVINCE', 'OCCUPANCY_DATE', 'OCCUPANCY_RATE_BEDS', 'OCCUPANCY_RATE_ROOMS', 'OCCUPIED_BEDS', 'OCCUPIED_ROOMS', 'ORGANIZATION_ID', 'ORGANIZATION_NAME', 'OVERNIGHT_SERVICE_TYPE', 'PROGRAM_AREA', 'PROGRAM_ID', 'PROGRAM_MODEL', 'PROGRAM_NAME', 'SECTOR', 'SERVICE_USER_COUNT', 'SHELTER_GROUP', 'SHELTER_ID', 'UNAVAILABLE_BEDS', 'UNAVAILABLE_ROOMS', 'UNOCCUPIED_BEDS', 'UNOCCUPIED_ROOMS', 'Longitude (x)', 'Latitude (y)', 'Station Name', 'Climate ID', 'Date/Time', 'Year', 'Month', 'Day', 'Data Quality', 'Max Temp (Â°C)', 'Max Temp Flag', 'Min Temp (Â°C)', 'Min Temp Flag', 'Mean Temp (Â°C)', 'Mean Temp Flag', 'Heat Deg Days (Â°C)', 'Heat Deg Days Flag', 'Cool Deg Days (Â°C)', 'Cool Deg Days Flag', 'Total Rain (mm)', 'Total Rain Flag', 'Total Snow (cm)', 'Total Snow Flag', 'Total Precip (mm)', 'Total Precip Flag', 'Snow on Grnd (cm)', 'Snow on Grnd Flag', 'Dir of Max Gust (10s deg)', 'Dir of Max Gust Flag', 'Spd of Max Gust (km/h)', 'Spd of Max Gust Flag']

In [200]:
df1.drop(columns=['_id','Source of Infection'],inplace=True)

In [201]:
## Clean date and specified date format
df1['Date']=pd.to_datetime(df1.Date)


print(df1['Date'])

0     2022-01-14
1     2022-01-14
2     2022-01-14
3     2022-01-14
4     2022-01-14
         ...
360          NaT
361          NaT
362          NaT
363          NaT
364          NaT
Name: Date, Length: 306887, dtype: datetime64[ns]

In [202]:
df1['Date'].isnull().values.any()

True

In [203]:
df1['Date'].isnull().values.sum()

11783

In [204]:
df1['Date/Time']=pd.to_datetime(df1.Date)


print(df1['Date/Time'])

0     2022-01-14
1     2022-01-14
2     2022-01-14
3     2022-01-14
4     2022-01-14
         ...
360          NaT
361          NaT
362          NaT
363          NaT
364          NaT
Name: Date/Time, Length: 306887, dtype: datetime64[ns]

In [205]:
df1['Date/Time'].isnull().values.sum()

11783

In [206]:
df1.dropna(how='all')

,Age Group,Assigned_ID,Gender,Episode Date,FSA,Outbreak Associated,Date,CAPACITY_ACTUAL_BED,CAPACITY_ACTUAL_ROOM,CAPACITY_FUNDING_BED,...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,20 to 29 Years,265244.0,MALE,2022-01-14T00:00:00,M6H,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,50 to 59 Years,265245.0,MALE,2022-01-13T00:00:00,M6K,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,30 to 39 Years,265246.0,MALE,2022-01-08T00:00:00,M6G,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,40 to 49 Years,265247.0,FEMALE,2022-01-13T00:00:00,M6P,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,30 to 39 Years,265248.0,UNKNOWN,2022-01-14T00:00:00,M6K,Outbreak Associated,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,4.6,NaN,3.6,NaN,4.0,E,9.0,NaN,48.0,NaN
361,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,0.2,NaN,0.2,NaN,2.0,NaN,26.0,NaN,57.0,NaN
362,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,0.0,T,0.2,NaN,1.0,NaN,NaN,M,NaN,M
363,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,0.0,NaN,0.0,NaN,NaN,NaN,NaN,M,NaN,M
364,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,...,0.0,NaN,0.0,T,NaN,NaN,NaN,M,NaN,M

In [207]:
df1.head(60)

,Age Group,Assigned_ID,Gender,Episode Date,FSA,Outbreak Associated,Date,CAPACITY_ACTUAL_BED,CAPACITY_ACTUAL_ROOM,CAPACITY_FUNDING_BED,...,Total Snow (cm),Total Snow Flag,Total Precip (mm),Total Precip Flag,Snow on Grnd (cm),Snow on Grnd Flag,Dir of Max Gust (10s deg),Dir of Max Gust Flag,Spd of Max Gust (km/h),Spd of Max Gust Flag
0,20 to 29 Years,265244.0,MALE,2022-01-14T00:00:00,M6H,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,50 to 59 Years,265245.0,MALE,2022-01-13T00:00:00,M6K,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,30 to 39 Years,265246.0,MALE,2022-01-08T00:00:00,M6G,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,40 to 49 Years,265247.0,FEMALE,2022-01-13T00:00:00,M6P,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,30 to 39 Years,265248.0,UNKNOWN,2022-01-14T00:00:00,M6K,Outbreak Associated,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,20 to 29 Years,265249.0,MALE,2022-01-07T00:00:00,M1R,Sporadic,2022-01-10,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,70 to 79 Years,265250.0,FEMALE,2022-01-13T00:00:00,M1K,Outbreak Associated,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,50 to 59 Years,265251.0,FEMALE,2022-01-14T00:00:00,M4V,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,19 and younger,265252.0,UNKNOWN,2022-01-10T00:00:00,M5M,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,20 to 29 Years,265253.0,MALE,2021-12-28T00:00:00,M1K,Sporadic,2022-01-12,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,30 to 39 Years,265254.0,FEMALE,2022-01-14T00:00:00,NaN,Outbreak Associated,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,30 to 39 Years,265255.0,MALE,2021-12-31T00:00:00,M1M,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,60 to 69 Years,265256.0,FEMALE,2022-01-10T00:00:00,M3L,Outbreak Associated,2022-01-13,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,40 to 49 Years,265257.0,FEMALE,2022-01-07T00:00:00,M4C,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,30 to 39 Years,265258.0,MALE,2021-12-29T00:00:00,M4K,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,50 to 59 Years,265259.0,MALE,2022-01-07T00:00:00,M9A,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,30 to 39 Years,265388.0,MALE,2022-01-12T00:00:00,M1M,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,30 to 39 Years,265260.0,FEMALE,2021-12-29T00:00:00,M3C,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,60 to 69 Years,265261.0,FEMALE,2021-12-29T00:00:00,M3C,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,70 to 79 Years,265262.0,MALE,2021-12-30T00:00:00,M9W,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20 to 29 Years,265263.0,FEMALE,2021-12-29T00:00:00,M6S,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,50 to 59 Years,265264.0,FEMALE,2022-01-13T00:00:00,M3C,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,30 to 39 Years,265265.0,MALE,2022-01-13T00:00:00,M1T,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,19 and younger,265266.0,FEMALE,2021-12-30T00:00:00,M5J,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,40 to 49 Years,265267.0,MALE,2022-01-13T00:00:00,M6K,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,40 to 49 Years,265268.0,FEMALE,2022-01-13T00:00:00,M3H,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,30 to 39 Years,265269.0,FEMALE,2021-12-30T00:00:00,M5V,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,30 to 39 Years,265270.0,MALE,2021-12-30T00:00:00,M5J,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,50 to 59 Years,265271.0,FEMALE,2022-01-11T00:00:00,M6J,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,20 to 29 Years,265272.0,MALE,2022-01-03T00:00:00,M9C,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,40 to 49 Years,265273.0,MALE,2022-01-03T00:00:00,M6S,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,20 to 29 Years,265274.0,MALE,2021-12-30T00:00:00,M8V,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,30 to 39 Years,265275.0,MALE,2022-01-03T00:00:00,M8V,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,30 to 39 Years,265276.0,MALE,2021-12-30T00:00:00,M5V,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,20 to 29 Years,265277.0,FEMALE,2021-12-30T00:00:00,M5J,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,30 to 39 Years,265278.0,MALE,2021-12-30T00:00:00,M5V,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,50 to 59 Years,265279.0,MALE,2022-01-13T00:00:00,M9M,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,60 to 69 Years,265280.0,MALE,2021-12-30T00:00:00,M9A,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,50 to 59 Years,265281.0,MALE,2021-12-30T00:00:00,M9B,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,50 to 59 Years,265282.0,MALE,2022-01-13T00:00:00,M6A,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,40 to 49 Years,265283.0,FEMALE,2022-01-13T00:00:00,M3N,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,50 to 59 Years,265284.0,FEMALE,2022-01-12T00:00:00,M9A,Outbreak Associated,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,70 to 79 Years,265285.0,FEMALE,2022-01-13T00:00:00,M6L,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,30 to 39 Years,265286.0,FEMALE,2022-01-11T00:00:00,M6B,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,20 to 29 Years,265287.0,FEMALE,2022-01-12T00:00:00,M3N,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,70 to 79 Years,265288.0,MALE,2022-01-13T00:00:00,M2R,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,70 to 79 Years,265289.0,MALE,2022-01-13T00:00:00,M6L,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,30 to 39 Years,265290.0,FEMALE,2022-01-08T00:00:00,M3J,Outbreak Associated,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,50 to 59 Years,265291.0,MALE,2022-01-13T00:00:00,M6M,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,19 and younger,265292.0,MALE,2021-12-29T00:00:00,M6M,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,20 to 29 Years,265293.0,FEMALE,2021-12-30T00:00:00,M9V,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,70 to 79 Years,265294.0,MALE,2022-01-13T00:00:00,M3M,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,40 to 49 Years,265295.0,MALE,2022-01-13T00:00:00,M3N,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,20 to 29 Years,265296.0,MALE,2021-12-30T00:00:00,M9W,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,19 and younger,265297.0,UNKNOWN,2022-01-10T00:00:00,M2K,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,30 to 39 Years,265298.0,FEMALE,2022-01-13T00:00:00,M9V,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,40 to 49 Years,265299.0,FEMALE,2021-12-30T00:00:00,M3H,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,50 to 59 Years,265300.0,MALE,2022-01-13T00:00:00,M3H,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,30 to 39 Years,265301.0,FEMALE,2021-12-24T00:00:00,M3C,Sporadic,2022-01-12,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,19 and younger,265302.0,MALE,2021-12-30T00:00:00,M9W,Sporadic,2022-01-14,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [208]:
print(df)

     Longitude (x)  Latitude (y)    Station Name  Climate ID   Date/Time  \
0           -79.63         43.68  TORONTO INTL A     6158731  2021-01-01
1           -79.63         43.68  TORONTO INTL A     6158731  2021-01-02
2           -79.63         43.68  TORONTO INTL A     6158731  2021-01-03
3           -79.63         43.68  TORONTO INTL A     6158731  2021-01-04
4           -79.63         43.68  TORONTO INTL A     6158731  2021-01-05
..             ...           ...             ...         ...         ...
360         -79.63         43.68  TORONTO INTL A     6158731  2021-12-27
361         -79.63         43.68  TORONTO INTL A     6158731  2021-12-28
362         -79.63         43.68  TORONTO INTL A     6158731  2021-12-29
363         -79.63         43.68  TORONTO INTL A     6158731  2021-12-30
364         -79.63         43.68  TORONTO INTL A     6158731  2021-12-31

     Year  Month  Day  Data Quality  Max Temp (Â°C)  ... Total Snow (cm)  \
0    2021      1    1           NaN            1.6  ...             3.0
1    2021      1    2           NaN            1.2  ...             4.0
2    2021      1    3           NaN            1.1  ...             1.4
3    2021      1    4           NaN            1.1  ...             0.0
4    2021      1    5           NaN            1.0  ...             0.2
..    ...    ...  ...           ...            ...  ...             ...
360  2021     12   27           NaN            0.1  ...             4.6
361  2021     12   28           NaN            2.3  ...             0.2
362  2021     12   29           NaN            2.2  ...             0.0
363  2021     12   30           NaN            2.2  ...             0.0
364  2021     12   31           NaN            6.7  ...             0.0

     Total Snow Flag Total Precip (mm)  Total Precip Flag Snow on Grnd (cm)  \
0                NaN               8.0                NaN               1.0
1                NaN               6.8                NaN               7.0
2                NaN               1.6                NaN               4.0
3                  T               0.0                  T               2.0
4                NaN               0.2                NaN               2.0
..               ...               ...                ...               ...
360              NaN               3.6                NaN               4.0
361              NaN               0.2                NaN               2.0
362                T               0.2                NaN               1.0
363              NaN               0.0                NaN               NaN
364              NaN               0.0                  T               NaN

     Snow on Grnd Flag Dir of Max Gust (10s deg)  Dir of Max Gust Flag  \
0                  NaN                      11.0                   NaN
1                  NaN                      33.0                   NaN
2                  NaN                       NaN                     M
3                  NaN                       NaN                     M
4                  NaN                       NaN                     M
..                 ...                       ...                   ...
360                  E                       9.0                   NaN
361                NaN                      26.0                   NaN
362                NaN                       NaN                     M
363                NaN                       NaN                     M
364                NaN                       NaN                     M

    Spd of Max Gust (km/h)  Spd of Max Gust Flag
0                     46.0                   NaN
1                     42.0                   NaN
2                      NaN                     M
3                      NaN                     M
4                      NaN                     M
..                     ...                   ...
360                   48.0                   NaN
361                   57.0                   NaN
362                    NaN                     M
363                    NaN                     M
364                    NaN                     M

[365 rows x 31 columns]

# covid 19 date cleaning